title: SongNgư.xyz
email: admin@songngu.xyz
description: > # this means to ignore newlines until "baseurl:"
  Đài tiếng nói ước mơ của bạn
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://songngu.xyz" # the base hostname & protocol for your site, e.g. http://example.com

# google-site-verification: edJRgAhGidylXbXZu05J3aRBcd45ICOap3iqyossp00
lang: vi_VN
timezone: Asia/Ho_Chi_Minh

sass:
  load_paths:
    - _sass
    - node_modules
    - styles

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - scripts
  - node_modules
# include:
#   - ads.txt
